name: NPM Installation

on:
  push:
    branches-ignore:
      - "dependabot/**"

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install npm dependencies
        run: npm install

      - name: Run build
        run: npm run build